### ISSUE TITLE
Nothing has happened yet

### ISSUE THREAD

**Issue by heltonbiker** [heltonbiker/MapComplete#1]
This project has started, but nothing has happened yet. It is necessary to do something about it.

**Comment by markph0204** [comment]
The license file is too restrictive. :8ball:

**Comment by heltonbiker** [comment]
@markph0204 do you still have interest in this project? I surely could do something about it.

I have only seen this message today, sorry. And that's because I started to use GutHub professionally (my employer decided to migrate), so I believe I could have a bit more energy to move things around with this project.

**Comment by heltonbiker** [comment]
@markph0204, I have updated the license from Apache to MIT. Does it solve the issue?

Thanks for your feedback. What do you think should be done next? Feel free to add an issue, or otherwise contact me somehow (preferrably here, I guess)
